import turtle,random
turtle.mode("logo")
turtle.shape("turtle")
turtle.fillcolor("green")

turtle.colormode(255)
turtle.speed(100)
turtle.pencolor(146,25,32)
unit=80
def move(x,y):
    turtle.pu()
    turtle.goto(x,y)
    turtle.pd()
    turtle.pensize(random.randint(2,5))

move(-200,200)
turtle.seth(180)
turtle.forward(400)
turtle.left(90)
turtle.forward(400)
turtle.left(90)
turtle.forward(400)
turtle.left(90)
turtle.forward(350)
turtle.seth(0)
move(-120,-200)
turtle.forward(unit)
move(-40,-120)
turtle.forward(unit)
move(40,-200)
turtle.forward(unit)
move(120,-120)
turtle.forward(unit)
move(-40,40)
turtle.forward(unit)
move(120,120)
turtle.forward(unit)
move(-200,120)
turtle.seth(90)
turtle.forward(3*unit)
turtle.right(90)
turtle.forward(unit)
turtle.left(90)
turtle.forward(unit)
turtle.right(90)
turtle.forward(unit)
turtle.right(90)
turtle.forward(3*unit)
turtle.right(90)
turtle.forward(unit)
turtle.forward(80)
turtle.pu()
turtle.goto(-180,230)
turtle.pd()
turtle.pensize(0)
turtle.seth(90)
turtle.fillcolor('green')
turtle.begin_fill()
for i in range(5):
    turtle.left(72)
    turtle.forward(15)
    turtle.right(144)
    turtle.forward(15)

turtle.end_fill()
turtle.seth(0)
move(80,80)
turtle.speed(1)
turtle.pencolor("blue")



###练习代码
turtle.forward(80)
turtle.left(90)
turtle.forward(240)
turtle.right(90)
turtle.forward(80)
######

turtle.done()