import turtle
turtle.mode("logo")
turtle.shape("turtle")
turtle.pu()
turtle.goto(20,30)
turtle.pd()
turtle.pencolor('green')
turtle.forward(100)
turtle.dot(30)


turtle.pu()
turtle.goto(0,-10)
turtle.pd()
turtle.pencolor('red')
turtle.forward(100)
turtle.dot(30)

turtle.pu()
turtle.goto(-30,50)
turtle.pd()
turtle.pencolor('blue')
turtle.forward(100)
turtle.dot(30)

turtle.pu()
turtle.goto(90,80)
turtle.pd()
turtle.pencolor('orange')
turtle.forward(100)
turtle.dot(30)
turtle.done()